import type { ThemeDefinition, ThemeId } from './themeTypes';
import { BASE_SPACING_TOKENS, BASE_MOTION_TOKENS } from './tokens';

export const ATELIER_THEME: ThemeDefinition = {
  id: 'atelier',
  version: 1,
  name: 'Atelier',
  tagline: 'Luxury, Editorial & Haute Boutique',
  description: 'Designed for fashion, fine jewellery, luxury beauty, and curated design houses where imagery and quiet elegance drive prestige.',
  idealFor: ['Luxury Fashion', 'Fine Jewellery', 'Cosmetics', 'Designer Studio', 'Boutique Fragrance'],
  aspectRatio: '3/4',
  colors: {
    primary: '#121212',
    primaryHover: '#2A2A2A',
    accent: '#D4AF37',
    accentHover: '#B8972E',
    background: '#FDFCF7',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    text: '#121212',
    textMuted: '#666666',
    textSubtle: '#8C8C8C',
    border: '#E8E4DC',
    borderSubtle: '#F0ECE4',
    badgeBg: '#121212',
    badgeText: '#FDFCF7',
    saleBadgeBg: '#121212',
    saleBadgeText: '#D4AF37',
  },
  typography: {
    display: 'clamp(2.5rem, 5vw, 4.25rem)',
    heading: 'clamp(1.75rem, 3.5vw, 2.5rem)',
    subheading: 'clamp(1.125rem, 2vw, 1.375rem)',
    body: '0.9375rem',
    bodySmall: '0.8125rem',
    label: '0.6875rem',
    caption: '0.625rem',
    price: '1.125rem',
    navigation: '0.8125rem',
    fontFamilyHeading: "'Cormorant Garamond', 'Playfair Display', Georgia, serif",
    fontFamilyBody: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    headingWeight: '500',
    bodyWeight: '400',
    letterSpacingHeading: '0.04em',
    textTransformHeading: 'none',
  },
  spacing: {
    ...BASE_SPACING_TOKENS,
    sectionPadding: 'clamp(64px, 10vw, 120px)',
    cardGap: '32px',
  },
  radius: {
    none: '0px',
    sm: '0px',
    md: '0px',
    lg: '0px',
    pill: '0px',
    card: '0px',
    button: '0px',
    input: '0px',
  },
  elevation: {
    surface0: '#FDFCF7',
    surface1: '#FFFFFF',
    surface2: '#FFFFFF',
    floating: '#FFFFFF',
    modal: '#FFFFFF',
    shadowCard: '0 1px 3px rgba(0, 0, 0, 0.04)',
    shadowCardHover: '0 12px 32px rgba(0, 0, 0, 0.08)',
    shadowDropdown: '0 16px 40px rgba(0, 0, 0, 0.1)',
    shadowModal: '0 24px 60px rgba(0, 0, 0, 0.16)',
  },
  motion: BASE_MOTION_TOKENS,
  cardVariant: 'editorial',
  headerVariant: 'editorial',
  heroVariant: 'editorial',
  footerVariant: 'editorial',
  defaultSections: [
    {
      id: 'announcement-1',
      type: 'announcement',
      variant: 'minimal',
      enabled: true,
      config: {
        text: 'Complimentary white-glove dispatch on bespoke orders across India',
      },
    },
    {
      id: 'header-1',
      type: 'header',
      variant: 'editorial',
      enabled: true,
      config: {
        showSearch: true,
        showAccount: true,
      },
    },
    {
      id: 'hero-1',
      type: 'hero',
      variant: 'editorial',
      enabled: true,
      config: {
        eyebrow: 'Maison Collection 2026',
        headline: 'Quiet Sophistication, Enduring Craft',
        subheadline: 'Each piece is deliberately composed with artisanal precision and unyielding attention to material purity.',
        ctaText: 'Explore Collection',
        ctaHref: '#products',
      },
    },
    {
      id: 'trust-1',
      type: 'trust-strip',
      variant: 'luxury-guarantee',
      enabled: true,
      config: {
        badge1Title: 'Certificate of Authenticity',
        badge1Subtitle: 'Directly verified from verified ateliers',
        badge2Title: 'Bespoke Packaging',
        badge2Subtitle: 'Presented in archival signature boxes',
        badge3Title: 'Discreet Insured Transit',
        badge3Subtitle: 'Tamper-evident sealed delivery',
      },
    },
    {
      id: 'products-1',
      type: 'product-grid',
      variant: 'editorial',
      enabled: true,
      config: {
        title: 'Selected Curations',
        subtitle: 'Timeless works crafted for discerning collectors',
        columns: 3,
        showFilter: true,
      },
    },
    {
      id: 'brand-story-1',
      type: 'brand-story',
      variant: 'quote-center',
      enabled: true,
      config: {
        quote: '“We do not manufacture for seasons. We cultivate artifacts meant to outlive trends and honor the hands that shaped them.”',
        author: 'The Creative Director',
      },
    },
    {
      id: 'newsletter-1',
      type: 'newsletter',
      variant: 'minimal',
      enabled: true,
      config: {
        title: 'The Atelier Dispatch',
        subtitle: 'Receive private invitations to preview new capsule releases before general exhibition.',
      },
    },
    {
      id: 'footer-1',
      type: 'footer',
      variant: 'editorial',
      enabled: true,
      config: {},
    },
  ],
};

export const MARKET_THEME: ThemeDefinition = {
  id: 'market',
  version: 1,
  name: 'Market',
  tagline: 'Modern Commerce & Maximum Efficiency',
  description: 'Built for high-velocity Indian retail, groceries, multi-category merchants, and electronics. High clarity, fast discovery, instant WhatsApp order triggers.',
  idealFor: ['Kirana & Grocery', 'Consumer Electronics', 'Supermarkets', 'General Retail', 'Multi-Category Stores'],
  aspectRatio: '1/1',
  colors: {
    primary: '#0F172A',
    primaryHover: '#1E293B',
    accent: '#16A34A',
    accentHover: '#15803D',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    text: '#0F172A',
    textMuted: '#475569',
    textSubtle: '#94A3B8',
    border: '#E2E8F0',
    borderSubtle: '#F1F5F9',
    badgeBg: '#DC2626',
    badgeText: '#FFFFFF',
    saleBadgeBg: '#FEF2F2',
    saleBadgeText: '#DC2626',
  },
  typography: {
    display: 'clamp(2rem, 4vw, 3rem)',
    heading: 'clamp(1.5rem, 3vw, 2rem)',
    subheading: 'clamp(1rem, 1.5vw, 1.1875rem)',
    body: '0.9375rem',
    bodySmall: '0.8125rem',
    label: '0.75rem',
    caption: '0.6875rem',
    price: '1.25rem',
    navigation: '0.875rem',
    fontFamilyHeading: "'Plus Jakarta Sans', 'Inter', system-ui, sans-serif",
    fontFamilyBody: "'Inter', system-ui, -apple-system, sans-serif",
    headingWeight: '700',
    bodyWeight: '400',
    letterSpacingHeading: '-0.02em',
    textTransformHeading: 'none',
  },
  spacing: {
    ...BASE_SPACING_TOKENS,
    sectionPadding: 'clamp(40px, 6vw, 72px)',
    cardGap: '16px',
  },
  radius: {
    none: '0px',
    sm: '4px',
    md: '6px',
    lg: '8px',
    pill: '9999px',
    card: '6px',
    button: '6px',
    input: '6px',
  },
  elevation: {
    surface0: '#F8FAFC',
    surface1: '#FFFFFF',
    surface2: '#FFFFFF',
    floating: '#FFFFFF',
    modal: '#FFFFFF',
    shadowCard: '0 1px 2px rgba(15, 23, 42, 0.05)',
    shadowCardHover: '0 8px 20px rgba(15, 23, 42, 0.08)',
    shadowDropdown: '0 12px 30px rgba(15, 23, 42, 0.12)',
    shadowModal: '0 20px 50px rgba(15, 23, 42, 0.18)',
  },
  motion: BASE_MOTION_TOKENS,
  cardVariant: 'clean',
  headerVariant: 'commerce',
  heroVariant: 'commerce-banner',
  footerVariant: 'commerce',
  defaultSections: [
    {
      id: 'announcement-1',
      type: 'announcement',
      variant: 'ticker',
      enabled: true,
      config: {
        text: '⚡ Free Express Delivery on orders above ₹499 | Cash on Delivery available at checkout | WhatsApp Orders: +91 98765 43210',
      },
    },
    {
      id: 'header-1',
      type: 'header',
      variant: 'commerce',
      enabled: true,
      config: {
        showSearch: true,
        showAccount: true,
        showCategories: true,
      },
    },
    {
      id: 'hero-1',
      type: 'hero',
      variant: 'commerce-banner',
      enabled: true,
      config: {
        eyebrow: 'DIRECT FROM VERIFIED SUPPLIERS',
        headline: 'Authentic Essentials. Best Local Prices.',
        subheadline: 'Shop fresh inventory with same-day dispatch and zero-hassle WhatsApp confirmation.',
        ctaText: 'Browse Catalog',
        ctaHref: '#products',
      },
    },
    {
      id: 'trust-1',
      type: 'trust-strip',
      variant: 'commerce-badges',
      enabled: true,
      config: {
        badge1Title: 'Cash on Delivery',
        badge1Subtitle: 'Pay at your doorstep',
        badge2Title: 'Direct Dispatch',
        badge2Subtitle: 'Directly from local warehouse',
        badge3Title: 'Instant WhatsApp Updates',
        badge3Subtitle: 'Live delivery code & OTP',
        badge4Title: 'Easy Returns',
        badge4Subtitle: 'Simple verification policy',
      },
    },
    {
      id: 'categories-1',
      type: 'category-grid',
      variant: 'visual-cards',
      enabled: true,
      config: {
        title: 'Top Categories',
      },
    },
    {
      id: 'products-1',
      type: 'product-grid',
      variant: 'clean',
      enabled: true,
      config: {
        title: 'Featured Products',
        subtitle: 'High demand essentials in stock right now',
        columns: 4,
        showFilter: true,
      },
    },
    {
      id: 'testimonials-1',
      type: 'testimonials',
      variant: 'verified-buyer-feed',
      enabled: true,
      config: {
        title: 'Trusted by Neighborhood Customers',
      },
    },
    {
      id: 'faq-1',
      type: 'faq',
      variant: 'accordion',
      enabled: true,
      config: {
        title: 'Frequently Asked Questions',
      },
    },
    {
      id: 'footer-1',
      type: 'footer',
      variant: 'commerce',
      enabled: true,
      config: {},
    },
  ],
};

export const MONO_THEME: ThemeDefinition = {
  id: 'mono',
  version: 1,
  name: 'Mono',
  tagline: 'Minimalist, Swiss & Architectural',
  description: 'Monochrome foundation, mathematical grid alignment, 1px rules, and tabular pricing. Built for technology, furniture, architecture, and design-first goods.',
  idealFor: ['Hardware & Tech', 'Industrial Design', 'Modern Furniture', 'Stationery', 'Audio Equipment'],
  aspectRatio: '1/1',
  colors: {
    primary: '#000000',
    primaryHover: '#18181B',
    accent: '#000000',
    accentHover: '#27272A',
    background: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceElevated: '#F4F4F5',
    text: '#000000',
    textMuted: '#52525B',
    textSubtle: '#71717A',
    border: '#E4E4E7',
    borderSubtle: '#F4F4F5',
    badgeBg: '#000000',
    badgeText: '#FFFFFF',
    saleBadgeBg: '#F4F4F5',
    saleBadgeText: '#000000',
  },
  typography: {
    display: 'clamp(2.5rem, 5vw, 4rem)',
    heading: 'clamp(1.75rem, 3vw, 2.25rem)',
    subheading: 'clamp(1.0625rem, 1.8vw, 1.25rem)',
    body: '0.9375rem',
    bodySmall: '0.8125rem',
    label: '0.75rem',
    caption: '0.6875rem',
    price: '1.0625rem',
    navigation: '0.8125rem',
    fontFamilyHeading: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    fontFamilyBody: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    headingWeight: '600',
    bodyWeight: '400',
    letterSpacingHeading: '-0.03em',
    textTransformHeading: 'none',
  },
  spacing: {
    ...BASE_SPACING_TOKENS,
    sectionPadding: 'clamp(48px, 8vw, 96px)',
    cardGap: '0px',
  },
  radius: {
    none: '0px',
    sm: '0px',
    md: '0px',
    lg: '0px',
    pill: '0px',
    card: '0px',
    button: '0px',
    input: '0px',
  },
  elevation: {
    surface0: '#FFFFFF',
    surface1: '#FFFFFF',
    surface2: '#FAFAFA',
    floating: '#FFFFFF',
    modal: '#FFFFFF',
    shadowCard: 'none',
    shadowCardHover: 'none',
    shadowDropdown: '0 4px 16px rgba(0, 0, 0, 0.08)',
    shadowModal: '0 16px 40px rgba(0, 0, 0, 0.12)',
  },
  motion: BASE_MOTION_TOKENS,
  cardVariant: 'mono',
  headerVariant: 'minimal',
  heroVariant: 'minimal',
  footerVariant: 'minimal',
  defaultSections: [
    {
      id: 'header-1',
      type: 'header',
      variant: 'minimal',
      enabled: true,
      config: {
        showSearch: true,
      },
    },
    {
      id: 'hero-1',
      type: 'hero',
      variant: 'minimal',
      enabled: true,
      config: {
        eyebrow: 'SYSTEM // 01',
        headline: 'Functional Objects for Contemplative Living',
        subheadline: 'Engineered without superfluous ornamentation. Pure geometry, tactile materials, honest utility.',
        ctaText: 'Index of Products',
        ctaHref: '#products',
      },
    },
    {
      id: 'products-1',
      type: 'product-grid',
      variant: 'mono',
      enabled: true,
      config: {
        title: 'Catalog',
        subtitle: 'All items currently in active manufacture',
        columns: 3,
        showFilter: true,
      },
    },
    {
      id: 'featured-1',
      type: 'featured-product',
      variant: 'spotlight',
      enabled: true,
      config: {
        eyebrow: 'DESIGN HIGHLIGHT',
        title: 'Precision Monolithic Architecture',
      },
    },
    {
      id: 'newsletter-1',
      type: 'newsletter',
      variant: 'minimal',
      enabled: true,
      config: {
        title: 'Technical Releases',
        subtitle: 'Notification of restocks and component archives.',
      },
    },
    {
      id: 'footer-1',
      type: 'footer',
      variant: 'minimal',
      enabled: true,
      config: {},
    },
  ],
};

export const BOLD_THEME: ThemeDefinition = {
  id: 'bold',
  version: 1,
  name: 'Bold',
  tagline: 'Contemporary Consumer Brand & High Energy',
  description: 'Vibrant color blocking, large display headlines, pill badges, and secondary image hover dynamics. Built for D2C lifestyle, apparel, and youth brands.',
  idealFor: ['Streetwear & Apparel', 'Activewear', 'Specialty Snacks', 'Youth Lifestyle', 'Cosmetics D2C'],
  aspectRatio: '4/5',
  colors: {
    primary: '#0B0F19',
    primaryHover: '#1F2937',
    accent: '#2563EB',
    accentHover: '#1D4ED8',
    background: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceElevated: '#F3F4F6',
    text: '#0B0F19',
    textMuted: '#4B5563',
    textSubtle: '#9CA3AF',
    border: '#E5E7EB',
    borderSubtle: '#F3F4F6',
    badgeBg: '#F43F5E',
    badgeText: '#FFFFFF',
    saleBadgeBg: '#EFF6FF',
    saleBadgeText: '#2563EB',
  },
  typography: {
    display: 'clamp(2.75rem, 6vw, 4.5rem)',
    heading: 'clamp(1.75rem, 3.5vw, 2.75rem)',
    subheading: 'clamp(1.125rem, 2vw, 1.375rem)',
    body: '0.9375rem',
    bodySmall: '0.8125rem',
    label: '0.75rem',
    caption: '0.6875rem',
    price: '1.25rem',
    navigation: '0.875rem',
    fontFamilyHeading: "'Plus Jakarta Sans', -apple-system, sans-serif",
    fontFamilyBody: "'Inter', -apple-system, sans-serif",
    headingWeight: '800',
    bodyWeight: '500',
    letterSpacingHeading: '-0.03em',
    textTransformHeading: 'none',
  },
  spacing: {
    ...BASE_SPACING_TOKENS,
    sectionPadding: 'clamp(56px, 8vw, 100px)',
    cardGap: '24px',
  },
  radius: {
    none: '0px',
    sm: '6px',
    md: '10px',
    lg: '16px',
    pill: '9999px',
    card: '12px',
    button: '9999px',
    input: '10px',
  },
  elevation: {
    surface0: '#FFFFFF',
    surface1: '#FFFFFF',
    surface2: '#F8FAFC',
    floating: '#0B0F19',
    modal: '#FFFFFF',
    shadowCard: '0 4px 14px rgba(11, 15, 25, 0.04)',
    shadowCardHover: '0 16px 36px rgba(11, 15, 25, 0.1)',
    shadowDropdown: '0 16px 40px rgba(11, 15, 25, 0.14)',
    shadowModal: '0 24px 64px rgba(11, 15, 25, 0.22)',
  },
  motion: BASE_MOTION_TOKENS,
  cardVariant: 'bold',
  headerVariant: 'bold',
  heroVariant: 'product-focused',
  footerVariant: 'bold',
  defaultSections: [
    {
      id: 'announcement-1',
      type: 'announcement',
      variant: 'ticker',
      enabled: true,
      config: {
        text: '🔥 DROP 03 NOW LIVE // NATIONWIDE EXPRESS DISPATCH // ZERO COMPROMISE ON QUALITY',
      },
    },
    {
      id: 'header-1',
      type: 'header',
      variant: 'bold',
      enabled: true,
      config: {
        showSearch: true,
        showAccount: true,
      },
    },
    {
      id: 'hero-1',
      type: 'hero',
      variant: 'product-focused',
      enabled: true,
      config: {
        eyebrow: 'NEW ARRIVALS 2026',
        headline: 'Engineered for Action. Designed to Turn Heads.',
        subheadline: 'Crafted with premium high-density fabrics and structured silhouettes for everyday dominance.',
        ctaText: 'Shop the Drop',
        ctaHref: '#products',
      },
    },
    {
      id: 'categories-1',
      type: 'category-grid',
      variant: 'pill-slider',
      enabled: true,
      config: {
        title: 'Explore Categories',
      },
    },
    {
      id: 'products-1',
      type: 'product-grid',
      variant: 'bold',
      enabled: true,
      config: {
        title: 'Trending Drops',
        subtitle: 'Our highest-velocity pieces right now',
        columns: 3,
        showFilter: true,
      },
    },
    {
      id: 'brand-story-1',
      type: 'brand-story',
      variant: 'split-right-image',
      enabled: true,
      config: {
        eyebrow: 'THE MANIFESTO',
        title: 'Born in India. Built for the Modern World.',
        body: 'We reject generic fast fashion and disposable quality. Every garment is field-tested, colorfast, and made to withstand daily movement.',
      },
    },
    {
      id: 'testimonials-1',
      type: 'testimonials',
      variant: 'grid-cards',
      enabled: true,
      config: {
        title: 'Community Verified',
      },
    },
    {
      id: 'newsletter-1',
      type: 'newsletter',
      variant: 'bold',
      enabled: true,
      config: {
        title: 'Join the Inner Circle',
        subtitle: 'First access to drops, secret restocks, and exclusive community discounts.',
      },
    },
    {
      id: 'footer-1',
      type: 'footer',
      variant: 'bold',
      enabled: true,
      config: {},
    },
  ],
};

export const ARTISAN_THEME: ThemeDefinition = {
  id: 'artisan',
  version: 1,
  name: 'Artisan',
  tagline: 'Craft, Storytelling & Heritage Warmth',
  description: 'Warm earth tones, tactile surfaces, maker storytelling sections, and authentic craft badges. Perfect for handmade goods, organic food, ceramics, and regional heritage.',
  idealFor: ['Handcrafted Goods', 'Organic Gourmet', 'Regional Textiles', 'Ceramics & Home', 'Artisanal Tea & Coffee'],
  aspectRatio: '4/5',
  colors: {
    primary: '#2C221E',
    primaryHover: '#42332D',
    accent: '#C25E3E',
    accentHover: '#A64B2F',
    background: '#FBF8F3',
    surface: '#FFFFFF',
    surfaceElevated: '#F5EFE6',
    text: '#2C221E',
    textMuted: '#6D5B52',
    textSubtle: '#9E8A80',
    border: '#E7DFD5',
    borderSubtle: '#F0EAE2',
    badgeBg: '#C25E3E',
    badgeText: '#FFFFFF',
    saleBadgeBg: '#F5EAE4',
    saleBadgeText: '#C25E3E',
  },
  typography: {
    display: 'clamp(2.25rem, 4.5vw, 3.75rem)',
    heading: 'clamp(1.625rem, 3.2vw, 2.25rem)',
    subheading: 'clamp(1.0625rem, 1.8vw, 1.25rem)',
    body: '0.9375rem',
    bodySmall: '0.8125rem',
    label: '0.75rem',
    caption: '0.6875rem',
    price: '1.1875rem',
    navigation: '0.875rem',
    fontFamilyHeading: "'Playfair Display', 'Cormorant Garamond', Georgia, serif",
    fontFamilyBody: "'Inter', -apple-system, sans-serif",
    headingWeight: '600',
    bodyWeight: '400',
    letterSpacingHeading: '0.01em',
    textTransformHeading: 'none',
  },
  spacing: {
    ...BASE_SPACING_TOKENS,
    sectionPadding: 'clamp(56px, 8vw, 104px)',
    cardGap: '28px',
  },
  radius: {
    none: '0px',
    sm: '4px',
    md: '8px',
    lg: '12px',
    pill: '9999px',
    card: '8px',
    button: '6px',
    input: '6px',
  },
  elevation: {
    surface0: '#FBF8F3',
    surface1: '#FFFFFF',
    surface2: '#F5EFE6',
    floating: '#2C221E',
    modal: '#FFFFFF',
    shadowCard: '0 2px 8px rgba(44, 34, 30, 0.04)',
    shadowCardHover: '0 12px 28px rgba(44, 34, 30, 0.09)',
    shadowDropdown: '0 16px 36px rgba(44, 34, 30, 0.12)',
    shadowModal: '0 24px 56px rgba(44, 34, 30, 0.18)',
  },
  motion: BASE_MOTION_TOKENS,
  cardVariant: 'artisan',
  headerVariant: 'artisan',
  heroVariant: 'artisan-story',
  footerVariant: 'artisan',
  defaultSections: [
    {
      id: 'announcement-1',
      type: 'announcement',
      variant: 'static-center',
      enabled: true,
      config: {
        text: 'Handcrafted in small batches • 100% plastic-free packaging • Direct from master artisans',
      },
    },
    {
      id: 'header-1',
      type: 'header',
      variant: 'artisan',
      enabled: true,
      config: {
        showSearch: true,
        showAccount: true,
      },
    },
    {
      id: 'hero-1',
      type: 'hero',
      variant: 'artisan-story',
      enabled: true,
      config: {
        eyebrow: 'HEIRLOOM TRADITIONS',
        headline: 'Crafted with Patience. Cherished for Generations.',
        subheadline: 'Every batch is prepared with heritage methods, unadulterated natural materials, and fair living wages for our artisan families.',
        ctaText: 'Discover Our Craft',
        ctaHref: '#products',
      },
    },
    {
      id: 'trust-1',
      type: 'trust-strip',
      variant: 'artisan-values',
      enabled: true,
      config: {
        badge1Title: 'Direct From Makers',
        badge1Subtitle: 'Fair compensation without middlemen',
        badge2Title: 'Small Batch Production',
        badge2Subtitle: 'Made with deliberate attention to detail',
        badge3Title: 'Earth Friendly',
        badge3Subtitle: 'Compostable and plastic-free packaging',
      },
    },
    {
      id: 'categories-1',
      type: 'category-grid',
      variant: 'editorial-cards',
      enabled: true,
      config: {
        title: 'Curated Craft Collections',
      },
    },
    {
      id: 'products-1',
      type: 'product-grid',
      variant: 'artisan',
      enabled: true,
      config: {
        title: 'Handmade Creations',
        subtitle: 'Limited pieces currently available from our workshop',
        columns: 3,
        showFilter: true,
      },
    },
    {
      id: 'brand-story-1',
      type: 'brand-story',
      variant: 'heritage-story',
      enabled: true,
      config: {
        eyebrow: 'FROM OUR WORKSHOP',
        title: 'Honoring centuries of regional mastery',
        body: 'When you take home an item from our workshop, you preserve a tradition passed through five generations. We work directly with master craftspeople in their native villages, ensuring sacred techniques continue to thrive.',
      },
    },
    {
      id: 'testimonials-1',
      type: 'testimonials',
      variant: 'editorial-quote',
      enabled: true,
      config: {
        title: 'Words from Our Patrons',
      },
    },
    {
      id: 'faq-1',
      type: 'faq',
      variant: 'accordion',
      enabled: true,
      config: {
        title: 'Artisan Care & Inquiries',
      },
    },
    {
      id: 'footer-1',
      type: 'footer',
      variant: 'artisan',
      enabled: true,
      config: {},
    },
  ],
};

export const THEME_REGISTRY: Record<ThemeId, ThemeDefinition> = {
  atelier: ATELIER_THEME,
  market: MARKET_THEME,
  mono: MONO_THEME,
  bold: BOLD_THEME,
  artisan: ARTISAN_THEME,
};

export const THEMES_LIST: ThemeDefinition[] = [
  ATELIER_THEME,
  MARKET_THEME,
  MONO_THEME,
  BOLD_THEME,
  ARTISAN_THEME,
];
