export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মৈতৈলোন্' },
  { code: 'brx', name: 'Bodo', nativeName: 'बर' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'کٲशُر' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي' },
  { code: 'sat', name: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ' }
];

// Base dictionary for translation
const EN_DICT: Record<string, string> = {
  dashboard: 'Dashboard',
  products: 'Products',
  orders: 'Orders',
  analytics: 'Analytics',
  aiAssistant: 'AI Assistant',
  aiCredits: 'AI Credits',
  websiteBuilder: 'Website Builder',
  logout: 'Logout',
  settings: 'Settings',
  addProduct: 'Add Product',
  totalRevenue: 'Total Revenue',
  totalOrders: 'Total Orders',
  pendingOrders: 'Pending Orders',
  lowStock: 'Low Stock',
  viewAll: 'View All',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  search: 'Search',
  loading: 'Loading...',
  noData: 'No data found',
  free: 'Trial',
  basic: 'Basic',
  standard: 'Standard',
  pro: 'Pro',
  premium: 'Premium',
  upgrade: 'Upgrade Plan',
  typeMessage: 'Type a message or use voice...',
  send: 'Send',
  listen: 'Listening...',
  generating: 'Generating website...',
  publishWebsite: 'Publish Website',
  unpublishWebsite: 'Unpublish Website',
  yourSubdomain: 'Your Store URL',
  freePlan: '7-day Trial',
  basicPlan: 'Basic Plan',
  standardPlan: 'Standard Plan',
  proPlan: 'Pro Plan',
  premiumPlan: 'Premium Plan',
  support: 'Support',
  tickets: 'Tickets',
  raiseTicket: 'Raise Ticket',
  status: 'Status',
  actions: 'Actions',
  finish: 'Finish',
  next: 'Next',
  skip: 'Skip',
  welcome: 'Welcome to Fera',
  businessName: 'Business Name',
  businessType: 'Business Type',
  description: 'Description',
  targetAudience: 'Target Audience',
  mainProducts: 'Main Products',
  preferredLanguage: 'Preferred Language',
  phone: 'Phone Number',
  profileUpdated: '✨ Profile updated! Let\'s build your store',
  profileSaveFailed: 'Failed to save profile',
  pleaseAnswer: 'Please answer this question',
  addFirstProduct: 'Add Your First Product',
  chooseTemplate: 'Choose a Website Template',
  personalizeStore: 'Personalize Your Store',
  goLive: 'Go Live!',
  businessNamePlaceholder: 'e.g., Raj\'s Kirana Store',
  businessTypePlaceholder: 'e.g., Grocery, Fashion',
  descriptionPlaceholder: 'e.g., We sell fresh vegetables',
  targetAudiencePlaceholder: 'e.g., Local residents',
  mainProductsPlaceholder: 'e.g., Vegetables, Milk',
  preferredLanguagePlaceholder: 'English'
};

// Expanded translations for major Indian languages
export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: EN_DICT,
  hi: {
    dashboard: 'डैशबोर्ड',
    products: 'उत्पाद',
    orders: 'ऑर्डर',
    analytics: 'विश्लेषण',
    aiAssistant: 'AI सहायक',
    websiteBuilder: 'वेबसाइट बिल्डर',
    logout: 'लॉग आउट',
    settings: 'सेटिंग्स',
    addProduct: 'उत्पाद जोड़ें',
    totalRevenue: 'कुल राजस्व',
    totalOrders: 'कुल ऑर्डर',
    pendingOrders: 'लंबित ऑर्डर',
    lowStock: 'कम स्टॉक',
    viewAll: 'सभी देखें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    search: 'खोजें',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा नहीं मिला',
    free: 'ट्रायल',
    premium: 'प्रीमियम',
    upgrade: 'प्रीमियम पर अपग्रेड करें',
    typeMessage: 'संदेश टाइप करें या आवाज़ उपयोग करें...',
    send: 'भेजें',
    listen: 'सुन रहा है...',
    generating: 'वेबसाइट बना रहा है...',
    publishWebsite: 'वेबसाइट प्रकाशित करें',
    unpublishWebsite: 'अप्रकाशित करें',
    yourSubdomain: 'आपका स्टोर URL',
    freePlan: '7-दिवसीय ट्रायल',
    premiumPlan: 'प्रीमियम योजना',
    finish: 'समाप्त करें',
    next: 'अगला',
    skip: 'छोड़ें',
    welcome: 'फेरा में आपका स्वागत है'
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    products: 'ఉత్పత్తులు',
    orders: 'ఆర్డర్లు',
    analytics: 'విశ్లేషణ',
    aiAssistant: 'AI సహాయకుడు',
    websiteBuilder: 'వెబ్‌సైట్ బిల్డర్',
    logout: 'లాగౌట్',
    settings: 'సెట్టింగ్‌లు',
    addProduct: 'ఉత్పత్తిని జోడించు',
    totalRevenue: 'మొత్తం ఆదాయం',
    totalOrders: 'మొత్తం ఆర్డర్లు',
    pendingOrders: 'పెండింగ్ ఆర్డర్లు',
    lowStock: 'తక్కువ స్టాక్',
    viewAll: 'అన్నీ చూడండి',
    save: 'సేవ్',
    cancel: 'రద్దు',
    delete: 'తొలగించు',
    edit: 'సవరించు',
    search: 'శోధించు',
    loading: 'లోడ్ అవుతోంది...',
    noData: 'డేటా కనుగొనబడలేదు',
    free: 'ట్రయల్',
    premium: 'ప్రీమియం',
    upgrade: 'ప్రీమియంకు అప్‌గ్రేడ్ చేయండి',
    typeMessage: 'సందేశాన్ని టైప్ చేయండి...',
    send: 'పంపండి',
    listen: 'వింటున్నారు...',
    generating: 'వెబ్‌సైట్‌ను రూపొందిస్తున్నారు...',
    publishWebsite: 'వెబ్‌సైట్‌ను ప్రచురించండి',
    unpublishWebsite: 'ప్రచురణను రద్దు చేయండి',
    yourSubdomain: 'మీ స్టోర్ URL',
    freePlan: '7-రోజుల ట్రయల్',
    premiumPlan: 'ప్రీమియం ప్లాన్',
    finish: 'ముగించు',
    next: 'తరువాత',
    skip: 'వదిలేయండి'
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    products: 'தயாரிப்புகள்',
    orders: 'ஆர்டர்கள்',
    analytics: 'பகுப்பாய்வு',
    aiAssistant: 'AI உதவியாளர்',
    websiteBuilder: 'வலைதள உருவாக்கி',
    logout: 'வெளியேறு',
    settings: 'அமைப்புகள்',
    addProduct: 'தயாரிப்பு சேர்',
    totalRevenue: 'மொத்த வருவாய்',
    totalOrders: 'மொത്ത ஆர்டர்கள்',
    pendingOrders: 'நிலుவை ஆர்டர்கள்',
    lowStock: 'குறைந்த இருப்பு',
    viewAll: 'அனைத்தும் பார்',
    save: 'சேமி',
    cancel: 'ரத்து',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    search: 'தேடு',
    loading: 'ஏற்றுகிறது...',
    noData: 'தரவு இல்லை',
    free: 'சோதனை',
    premium: 'பிரீமியம்',
    upgrade: 'பிரீமியத்திற்கு மேம்படுத்தவும்',
    typeMessage: 'செய்தி தட்டச்சு செய்யுங்கள்...',
    send: 'அனுப்பு',
    listen: 'கேட்கிறது...',
    generating: 'வலைதளம் உருவாகிறது...',
    publishWebsite: 'வலைதளம் வெளியிடு',
    unpublishWebsite: 'வெளியீட்டை திரும்பப் பெறு',
    yourSubdomain: 'உங்கள் கடை URL',
    freePlan: '7 நாள் சோதனை',
    premiumPlan: 'பிரீமியம் திட்டம்',
    finish: 'முடிக்கவும்',
    next: 'அடுத்து',
    skip: 'தவிர்'
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    products: 'পণ্যসমূহ',
    orders: 'অর্ডারসমূহ',
    analytics: 'বিশ্লেষণ',
    aiAssistant: 'AI সহকারী',
    websiteBuilder: 'ওয়েবসাইট বিল্ডার',
    logout: 'লগআউট',
    settings: 'সেটিংস',
    addProduct: 'পণ্য যোগ করুন',
    totalRevenue: 'মোট রাজস্ব',
    totalOrders: 'মোট অর্ডার',
    viewAll: 'সব দেখুন',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল করুন',
    free: 'ট্রায়াল',
    freePlan: '৭-দিনের ট্রায়াল',
    premiumPlan: 'প্রিমিয়াম প্ল্যান',
    finish: 'শেষ করুন',
    next: 'পরবর্তী',
    skip: 'এড়িয়ে যান'
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    products: 'उत्पादने',
    orders: 'ऑर्डर्स',
    analytics: 'विश्लेषण',
    aiAssistant: 'AI सहाय्यक',
    websiteBuilder: 'वेबसाइट बिल्डर',
    logout: 'लॉगआउट',
    settings: 'सेटिंग्ज',
    addProduct: 'उत्पादन जोडा',
    totalRevenue: 'एकूण महसूल',
    totalOrders: 'एकूण ऑर्डर्स',
    viewAll: 'सर्व पहा',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    free: 'चाचणी',
    freePlan: '७ दिवसांची चाचणी',
    premiumPlan: 'प्रीमियम योजना',
    finish: 'पूर्ण करा',
    next: 'पुढील',
    skip: 'वगळा'
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    products: 'ઉત્પાદનો',
    orders: 'ઓર્ડર્સ',
    analytics: 'વિશ્લેષણ',
    aiAssistant: 'AI સહાયક',
    websiteBuilder: 'વેબસાઇટ બિલ્ડર',
    logout: 'લોગઆઉટ',
    settings: 'સેટિંગ્સ',
    addProduct: 'ઉત્પાદન ઉમેરો',
    totalRevenue: 'કુલ આવક',
    totalOrders: 'કુલ ઓર્ડર્સ',
    viewAll: 'બધું જુઓ',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    free: 'ટ્રાયલ',
    freePlan: '૭-દિવસીય ટ્રાયલ',
    premiumPlan: 'પ્રીમિયમ યોજના',
    finish: 'પૂર્ણ કરો',
    next: 'આગળ',
    skip: 'રદ કરો'
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    products: 'ಉತ್ಪನ್ನಗಳು',
    orders: 'ಆರ್ಡರ್‌ಗಳು',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    aiAssistant: 'AI ಸಹಾಯಕ',
    websiteBuilder: 'ವೆಬ್‌ಸೈಟ್ ಬಿಲ್ಡర్',
    logout: 'ಲಾಗ್ ಔಟ್',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    addProduct: 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    totalRevenue: 'ಒಟ್ಟು ಆದాయ',
    totalOrders: 'ಒಟ್ಟು ఆర్డర్‌ಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    free: 'ಪ್ರಾಯೋಗಿಕ',
    freePlan: '೭-ದಿನಗಳ ಪ್ರಾಯೋಗಿಕ',
    premiumPlan: 'ಪ್ರೀಮಿಯಂ ಯೋಜನೆ',
    finish: 'ಮುಗಿಸಿ',
    next: 'ಮುಂದೆ',
    skip: 'ಬಿಟ್ಟುಬಿಡಿ'
  },
  ml: {
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    products: 'ഉൽപ്പന്നങ്ങൾ',
    orders: 'ഓർഡറുകൾ',
    analytics: 'അനലിറ്റിക്സ്',
    aiAssistant: 'AI അസിസ്റ്റന്റ്',
    websiteBuilder: 'വെബ്സൈറ്റ് ബിൽഡർ',
    logout: 'ലോഗ് ഔട്ട്',
    settings: 'ക്രമീകരണങ്ങൾ',
    addProduct: 'ഉൽപ്പന്നം ചേർക്കുക',
    totalRevenue: 'ആകെ വരുമാനം',
    totalOrders: 'ആകെ ഓർഡറുകൾ',
    viewAll: 'എല്ലാം കാണുക',
    save: 'സേവ് ചെയ്യുക',
    cancel: 'റദ്ദാക്കുക',
    free: 'ട്രയൽ',
    freePlan: '7 ദിവസത്തെ ട്രയൽ',
    premiumPlan: 'പ്രീമിയం പ്ലാൻ',
    finish: 'പൂർത്തിയാക്കുക',
    next: 'അടുത്തത്',
    skip: 'ഒഴിവാക്കുക'
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    products: 'ਉਤਪਾਦ',
    orders: 'ਆਰਡਰ',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    aiAssistant: 'AI ਸਹਾਇਕ',
    websiteBuilder: 'ਵੈੱਬਸਾਈਟ ਬਿਲਡਰ',
    logout: 'ਲੌਗ ਆਊਟ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    addProduct: 'ਉਤਪਾਦ ਜੋੜੋ',
    totalRevenue: 'ਕੁੱਲ ਆਮਦਨ',
    totalOrders: 'ਕੁੱਲ ਆਰਡਰ',
    viewAll: 'ਸਾਰੇ ਦੇਖੋ',
    save: 'ਸੇਵ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    free: 'ਟ੍ਰਾਇਲ',
    freePlan: '7-ਦਿਨਾ ਟ੍ਰਾਇਲ',
    premiumPlan: 'ਪ੍ਰੀਮੀਅਮ ਯੋਜਨਾ',
    finish: 'ਖਤਮ ਕਰੋ',
    next: 'ਅਗਲਾ',
    skip: 'ਛੱਡੋ'
  }
};

export function t(key: string, language: string): string {
  // If we have the direct translation, use it
  if (UI_TRANSLATIONS[language] && UI_TRANSLATIONS[language][key]) {
    return UI_TRANSLATIONS[language][key];
  }
  
  // Fallback to English
  return UI_TRANSLATIONS.en[key] || key;
}
