export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মৈতৈলোন্' },
  { code: 'brx', name: 'Bodo', nativeName: 'बर' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'کٲشُر' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي' },
  { code: 'sat', name: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ' }
];

// Basic UI translations (extend with full i18n as needed)
export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    products: 'Products',
    orders: 'Orders',
    analytics: 'Analytics',
    aiAssistant: 'AI Assistant',
    websiteBuilder: 'Website Builder',
    logout: 'Logout',
    settings: 'Settings',
    addProduct: 'Add Product',
    totalRevenue: 'Total Revenue',
    totalOrders: 'Total Orders',
    pendingOrders: 'Pending Orders',
    lowStock: 'Low Stock',
    viewAll: 'View All',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    loading: 'Loading...',
    noData: 'No data found',
    free: 'Free',
    premium: 'Premium',
    upgrade: 'Upgrade to Premium',
    typeMessage: 'Type a message or use voice...',
    send: 'Send',
    listen: 'Listening...',
    generating: 'Generating website...',
    publishWebsite: 'Publish Website',
    unpublishWebsite: 'Unpublish Website',
    yourSubdomain: 'Your Store URL',
    freePlan: 'Free Plan',
    premiumPlan: 'Premium Plan'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    products: 'उत्पाद',
    orders: 'ऑर्डर',
    analytics: 'विश्लेषण',
    aiAssistant: 'AI सहायक',
    websiteBuilder: 'वेबसाइट बिल्डर',
    logout: 'लॉग आउट',
    settings: 'सेटिंग्स',
    addProduct: 'उत्पाद जोड़ें',
    totalRevenue: 'कुल राजस्व',
    totalOrders: 'कुल ऑर्डर',
    pendingOrders: 'लंबित ऑर्डर',
    lowStock: 'कम स्टॉक',
    viewAll: 'सभी देखें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    search: 'खोजें',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा नहीं मिला',
    free: 'मुफ्त',
    premium: 'प्रीमियम',
    upgrade: 'प्रीमियम पर अपग्रेड करें',
    typeMessage: 'संदेश टाइप करें या आवाज़ उपयोग करें...',
    send: 'भेजें',
    listen: 'सुन रहा है...',
    generating: 'वेबसाइट बना रहा है...',
    publishWebsite: 'वेबसाइट प्रकाशित करें',
    unpublishWebsite: 'अप्रकाशित करें',
    yourSubdomain: 'आपका स्टोर URL',
    freePlan: 'मुफ्त योजना',
    premiumPlan: 'प्रीमियम योजना'
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    products: 'தயாரிப்புகள்',
    orders: 'ஆர்டர்கள்',
    analytics: 'பகுப்பாய்வு',
    aiAssistant: 'AI உதவியாளர்',
    websiteBuilder: 'வலைதள உருவாக்கி',
    logout: 'வெளியேறு',
    settings: 'அமைப்புகள்',
    addProduct: 'தயாரிப்பு சேர்',
    totalRevenue: 'மொத்த வருவாய்',
    totalOrders: 'மொத்த ஆர்டர்கள்',
    pendingOrders: 'நிலுவை ஆர்டர்கள்',
    lowStock: 'குறைந்த இருப்பு',
    viewAll: 'அனைத்தும் பார்',
    save: 'சேமி',
    cancel: 'ரத்து',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    search: 'தேடு',
    loading: 'ஏற்றுகிறது...',
    noData: 'தரவு இல்லை',
    free: 'இலவசம்',
    premium: 'பிரீமியம்',
    upgrade: 'பிரீமியத்திற்கு மேம்படுத்தவும்',
    typeMessage: 'செய்தி தட்டச்சு செய்யுங்கள்...',
    send: 'அனுப்பு',
    listen: 'கேட்கிறது...',
    generating: 'வலைதளம் உருவாகிறது...',
    publishWebsite: 'வலைதளம் வெளியிடு',
    unpublishWebsite: 'வெளியீட்டை திரும்பப் பெறு',
    yourSubdomain: 'உங்கள் கடை URL',
    freePlan: 'இலவச திட்டம்',
    premiumPlan: 'பிரீமியம் திட்டம்'
  }
};

export function t(key: string, language: string): string {
  const translations = UI_TRANSLATIONS[language] || UI_TRANSLATIONS.en;
  return translations[key] || UI_TRANSLATIONS.en[key] || key;
}
